name: wstore
description: A state management library that helps add reactivity to widgets
version: 1.0.2
repository: https://github.com/devmaslove/wstore

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
